### ISSUE TITLE
Request: a way to capture Standard Output and Standard Error

### ISSUE THREAD

**Issue by itsho** [MichelMichels/CliSharp#1]
Hello.

How would you recommend to capture Standard Output and Standard Error from a running program?

code sample:

    Cli.SetProgram("git.exe").AddSwitch("status");

Thanks in advance

**Comment by MichelMichels** [comment]
I should look into that. I think I could capture it, but at the moment this
functionality is not supported. But I'd probably add an extension method if
I'd implement it.

Op ma 15 jun. 2020 08:32 schreef Itamar Shoham <notifications@github.com>:

**Comment by MichelMichels** [comment]
This has been implement in `v2.0.0`.
